openapi: '3.0.3'

info:
  title: motoo-lab-hobby
  version: 1.0.0

paths:
  /api/anime:
    get:
      responses:
        200:
          description: anime
          content:
            application/json:
              schema:
                type: object
                properties:
                  anime:
                    type: object
                    properties:
                      a:
                        $ref: "#/components/schemas/Anime"
                      ka:
                        $ref: "#/components/schemas/Anime"
                      sa:
                        $ref: "#/components/schemas/Anime"
                      ta:
                        $ref: "#/components/schemas/Anime"
                      na:
                        $ref: "#/components/schemas/Anime"
                      ha:
                        $ref: "#/components/schemas/Anime"
                      ma:
                        $ref: "#/components/schemas/Anime"
                      ya:
                        $ref: "#/components/schemas/Anime"
                      ra:
                        $ref: "#/components/schemas/Anime"
                      wa:
                        $ref: "#/components/schemas/Anime"
  /api/comic:
    get:
      responses:
        200:
          description: comic
          content:
            application/json:
              schema:
                type: object
                properties:
                  comic:
                    $ref: "#/components/schemas/Book"
  /api/novel:
    get:
      responses:
        200:
          description: novel
          content:
            application/json:
              schema:
                type: object
                properties:
                  novel:
                    $ref: "#/components/schemas/Book"

components:
  schemas:
    Anime:
      type: array
      items: 
        type: string
      example:
        - "あ"
        - "い"
    Book:
      type: array
      items: 
        type: string
      example: 
        - "漫画"
        - "コミック"
